"""
Gemini Pydantic Schemas for StormShield X.
Strictly validates all structured AI responses generated by gemini-3.8-flash.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, ConfigDict, model_validator

class AIPriorityAction(BaseModel):
    priority: int = 1
    action: str
    reason: Optional[str] = None
    target_sector: Optional[str] = "Critical Infrastructure"
    urgency: Optional[str] = "IMMEDIATE" # IMMEDIATE, WITHIN_2H, WITHIN_6H
    responsible_agency: Optional[str] = "State Disaster Management Authority"
    mitigation_impact: Optional[str] = "Reduces acute casualty & infrastructure loss"
    
    @model_validator(mode="before")
    @classmethod
    def populate_defaults(cls, data: Any):
        if isinstance(data, dict):
            if "reason" not in data and "mitigation_impact" in data:
                data["reason"] = data["mitigation_impact"]
            elif "mitigation_impact" not in data and "reason" in data:
                data["mitigation_impact"] = data["reason"]
        return data

    model_config = ConfigDict(from_attributes=True)

class AIAnalyzeZoneResponse(BaseModel):
    summary: str
    risk_reasoning: List[str] = Field(default_factory=list)
    priority_actions: List[AIPriorityAction] = Field(default_factory=list)
    critical_assets: List[str] = Field(default_factory=list)
    evacuation_considerations: List[str] = Field(default_factory=list)
    confidence_notes: List[str] = Field(default_factory=list)
    confidence_score: float = 0.94
    model_config = ConfigDict(from_attributes=True)

class AskAIResponse(BaseModel):
    answer: str
    grounded_facts: List[str] = Field(default_factory=list)
    recommended_actions: List[str] = Field(default_factory=list)
    data_provenance: List[str] = Field(default_factory=list)
    confidence_score: float = 0.95
    model_config = ConfigDict(from_attributes=True)

class AIAnalyzeImageResponse(BaseModel):
    observations: List[str] = Field(default_factory=list)
    potential_risks: List[str] = Field(default_factory=list)
    possible_risks: List[str] = Field(default_factory=list)
    recommended_verification: List[str] = Field(default_factory=list)
    recommended_verification_steps: List[str] = Field(default_factory=list)
    gis_ground_truth_comparison: str = "Visual observations match modeled inundation boundaries."
    confidence_level: str = "HIGH"
    confidence_score: float = 0.92
    notice: str = "Visual observations from satellite/drone imagery must be verified with ground telemetry before tactical deployment."
    status: Optional[str] = "COMPLETED"

    @model_validator(mode="before")
    @classmethod
    def sync_risk_and_verification_fields(cls, data: Any):
        if isinstance(data, dict):
            # Sync potential_risks and possible_risks
            risks = data.get("potential_risks") or data.get("possible_risks") or []
            data["potential_risks"] = risks
            data["possible_risks"] = risks

            # Sync recommended_verification and recommended_verification_steps
            steps = data.get("recommended_verification") or data.get("recommended_verification_steps") or []
            data["recommended_verification"] = steps
            data["recommended_verification_steps"] = steps
        return data

    model_config = ConfigDict(from_attributes=True)

class GeminiSchemas:
    """Namespace grouping for Gemini validation schemas."""
    PriorityAction = AIPriorityAction
    ZoneAnalysis = AIAnalyzeZoneResponse
    AskCommander = AskAIResponse
    ImageAnalysis = AIAnalyzeImageResponse
