import React from 'react';
import { 
  ShieldCheck, 
  Lock, 
  Eye, 
  FileText, 
  X, 
  CheckCircle2, 
  AlertCircle,
  Database,
  Cpu,
  Layers
} from 'lucide-react';

interface DataTrustModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DataTrustModal: React.FC<DataTrustModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  const provenanceBadges = [
    {
      badge: 'OFFICIAL',
      color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
      description: 'Verified real-time meteorological observations and cyclone tracks ingested from IMD, JTWC, and coastal tide gauge stations.'
    },
    {
      badge: 'SIMULATED',
      color: 'bg-red-500/20 text-red-300 border-red-500/30',
      description: 'Scenario parameters modeled to stress-test infrastructure capacity prior to landfall. Clearly designated to avoid confusion with official forecasts.'
    },
    {
      badge: 'SATELLITE',
      color: 'bg-sky-500/20 text-sky-300 border-sky-500/30',
      description: 'High-resolution Earth observation from Sentinel-1 SAR, Sentinel-2 Optical, and 30m ALOS/SRTM digital elevation models.'
    },
    {
      badge: 'MODEL',
      color: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
      description: 'Physics-based multi-hazard hydrodynamic equations computing flood accumulation, coastal wave overtopping, and wind shear decay.'
    },
    {
      badge: 'AI GENERATED',
      color: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
      description: 'Tactical decision-support briefs generated by Gemini and domain expert rules, grounded strictly in structured application metrics.'
    }
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md select-none">
      <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-700/80 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-800 bg-slate-950/80 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-600 to-teal-700 flex items-center justify-center text-white shadow-lg shadow-emerald-500/20">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h2 className="text-base font-bold text-slate-100">DATA TRUST & PROVENANCE CENTER</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  PRIVACY BY DESIGN
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Ethical AI commitments, data provenance architecture, and multi-hazard model transparency.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 text-xs">
          {/* Privacy By Design Core Principles */}
          <div className="space-y-3">
            <div className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center space-x-2">
              <Lock className="w-4 h-4 text-emerald-400" />
              <span>Sovereignty & Privacy-Preserving Architecture</span>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div className="p-3 bg-slate-950/70 border border-slate-800 rounded-xl space-y-1.5">
                <div className="font-semibold text-slate-200 flex items-center space-x-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Zero Raw Citizen Data Sharing</span>
                </div>
                <p className="text-slate-400 text-[11px] leading-relaxed">
                  Individual phone numbers, resident IDs, and private medical records are never aggregated or transmitted across network boundaries.
                </p>
              </div>

              <div className="p-3 bg-slate-950/70 border border-slate-800 rounded-xl space-y-1.5">
                <div className="font-semibold text-slate-200 flex items-center space-x-1.5">
                  <Eye className="w-3.5 h-3.5 text-blue-400" />
                  <span>Human-in-the-Loop Authority</span>
                </div>
                <p className="text-slate-400 text-[11px] leading-relaxed">
                  StormShield is an anticipatory decision-support prototype. It does not replace certified state disaster authority directives.
                </p>
              </div>

              <div className="p-3 bg-slate-950/70 border border-slate-800 rounded-xl space-y-1.5">
                <div className="font-semibold text-slate-200 flex items-center space-x-1.5">
                  <Database className="w-3.5 h-3.5 text-purple-400" />
                  <span>Decentralized Sovereign Nodes</span>
                </div>
                <p className="text-slate-400 text-[11px] leading-relaxed">
                  In BRICS cooperation mode, participating nations train models on local sovereign nodes and exchange only mathematical gradients.
                </p>
              </div>

              <div className="p-3 bg-slate-950/70 border border-slate-800 rounded-xl space-y-1.5">
                <div className="font-semibold text-slate-200 flex items-center space-x-1.5">
                  <Cpu className="w-3.5 h-3.5 text-amber-400" />
                  <span>Strictly Grounded Generative AI</span>
                </div>
                <p className="text-slate-400 text-[11px] leading-relaxed">
                  Gemini generates advice conditioned on structured numerical state. Hallucinated forecasts or ungrounded statistics are prohibited.
                </p>
              </div>
            </div>
          </div>

          {/* Data Provenance Badges System */}
          <div className="space-y-3">
            <div className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center space-x-2">
              <FileText className="w-4 h-4 text-blue-400" />
              <span>Standard Data Provenance Badges</span>
            </div>
            <div className="space-y-2">
              {provenanceBadges.map((item, idx) => (
                <div key={idx} className="p-2.5 bg-slate-950/60 border border-slate-800 rounded-lg flex items-start space-x-3">
                  <span className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold border shrink-0 ${item.color}`}>
                    {item.badge}
                  </span>
                  <p className="text-[11px] text-slate-300 leading-normal">
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Transparent Multi-Hazard Formula */}
          <div className="p-4 bg-slate-950/80 border border-slate-800 rounded-xl space-y-2">
            <div className="font-bold text-slate-200 flex items-center space-x-2">
              <Layers className="w-4 h-4 text-indigo-400" />
              <span>Transparent Composite Vulnerability Formulation</span>
            </div>
            <div className="p-2 bg-slate-900 font-mono text-[11px] text-slate-300 rounded border border-slate-800">
              Overall Risk = 0.30×Flood + 0.25×StormSurge + 0.20×Wind + 0.15×Criticality + 0.10×Isolation
            </div>
            <p className="text-[11px] text-slate-400">
              All weight factors are mathematically verifiable, transparent, and auditable by emergency risk engineers.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/90 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs cursor-pointer"
          >
            Close Trust Center
          </button>
        </div>
      </div>
    </div>
  );
};
